(fix) Bugfix. Stop if conda fails

diff --git a/install b/install
--- a/install
+++ b/install
@@ -22,17 +22,28 @@ else
     ${CONDA_EXE} env create -f "${_ENV_DIR}/${ENV_FILE}"
 fi
 
-# Record updated environment file
-${CONDA_EXE} env export -n ${ENV_NAME} > "${_ENV_DIR}/x-installed:${ENV_FILE}"
+if [ $? -ne 0 ]; then
+    echo "Failed to update the conda environment. Please resolve the above errors and try again."
+    exit 1
+fi
 
 source "${CONDA_BIN}/activate" ${ENV_NAME}
 
 # Installing conflicting pip packages without their dependencies
 # They could override the environment plan with conda
-echo "Installing conflicting pip packages without their dependencies"
-read -t 10 -p "Do you want to continue? [Y/n]: " RESPONSE
-if [ "${RESPONSE}_" == "_" ] || [ "${RESPONSE}" != "n" ]; then
-  python -m pip install --no-deps -r setup/pip_packages.txt 1> logs/pip_install.log 2>&1
+if [ "${ENV_NAME}" == "hummingbot-development" ]; then
+  echo "Skipping pip packages installation for development environment"
+else
+  echo "Installing conflicting pip packages without their dependencies"
+  read -t 10 -p "Do you want to continue? [Y/n]: " RESPONSE
+  if [ "${RESPONSE}_" == "_" ] || [ "${RESPONSE}" != "n" ]; then
+    python -m pip install --no-deps -r setup/pip_packages.txt 1> logs/pip_install.log 2>&1
+  fi
 fi
+
+# Record updated environment file
+${CONDA_EXE} env export -n ${ENV_NAME} > "${_ENV_DIR}/x-installed:${ENV_FILE}"
+# Directly reformat the exported environment file
+update_environment_yml "${_ENV_DIR}/${ENV_FILE}" "${_ENV_DIR}/x-installed:${ENV_FILE}" "${_ENV_DIR}/x-installed:${ENV_FILE}"
 
 pre-commit install
